public without sharing class CrmServiceRepository implements ICrmServiceRepository {
    public List<Crm_Service__c> getAllInProductionActiveCrmServices() 
    {
        // TODO: Implementation pending
        return null;
    }

    public List<Crm_Service__c> getAllCrmServices() {
        // TODO: Implementation pending
        return null;
    }

    public Crm_Service__c getCrmServicesByName(String serviceName) {
        // TODO: Implementation pending
        return null;
    }
}